name: TomTomSample
options:
  bundleIdPrefix: com.mapconductor.tomtomsample
  deploymentTarget:
    iOS: "16.0"
packages:
  ForTomTom:
    path: ..
  MapConductorCore:
    path: ../../ios-sdk-core
targets:
  TomTomSample:
    type: application
    platform: iOS
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: TomTom Sample
        UILaunchScreen: {}
        TomTomAPIKey: "8wcs2sqdWUZfoX6u9BW6tHKfpf0HuH5l"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    dependencies:
      - package: ForTomTom
        product: MapConductorForTomTom
      - package: MapConductorCore
        product: MapConductorCore
  TomTomSampleUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [UITests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TomTomSample
schemes:
  TomTomSample:
    build:
      targets:
        TomTomSample: all
        TomTomSampleUITests: [test]
    test:
      targets: [TomTomSampleUITests]
